# Noctalia theme for snappy-switcher

[colors]
background = #000000aa
card_bg = #131313aa
card_selected =  #282828ff
text_color = #d9e2ffdd
subtext_color =  #d9e2ffcc
border_color =  #919191ff
bundle_bg = #3f4759ff
badge_bg =  #bfc6dcaa
badge_text_color = #293042aa
badge_bg_selected = #bfc6dccc
badge_text_color_selected = #293042ff