# Noctalia theme for snappy-switcher

[colors]
background = #151311aa
card_bg = #211f1daa
card_selected =  #373432ff
text_color = #50402bdd
subtext_color =  #50402bcc
border_color =  #998f85ff
bundle_bg = #4e453bff
badge_bg =  #d1c4b7aa
badge_text_color = #372f26aa
badge_bg_selected = #d1c4b7cc
badge_text_color_selected = #372f26ff