# Noctalia theme for snappy-switcher

[colors]
background = #1c1e21aa
card_bg = #2f3337aa
card_selected =  #34383dff
text_color = #e4e5e7dd
subtext_color =  #e4e5e7cc
border_color =  #64696eff
bundle_bg = #363a49ff
badge_bg =  #8d92a5aa
badge_text_color = #1c1e22aa
badge_bg_selected = #8d92a5cc
badge_text_color_selected = #1c1e22ff