-- Colors template generated by Noctalia
-- Source command is:
-- dofile(os.getenv("HOME") .. "/.config/hypr/noctalia/noctalia-colors.lua")

local primary = "rgb(bfc8cc)"
local surface = "rgb(131314)"
local secondary = "rgb(c4c7c8)"
local error = "rgb(ffb4ab)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
