# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds
##! Window

##! Apps
# Add stuff here
bind = SUPER, SPACE, exec, walker # Albert launcher
bind = SUPER, O, exec, obsidian # Obsidian quick launch
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

bind = CTRL SHIFT, Escape, exec, kitty -e btop # Task manager (btop)

bind = SUPER, H, fullscreen, 1 # Toggle fullscreen (maximize)
bind = SUPER, R, exec, ambxst reload # Reload ambxst

# Start the daemon on login
exec-once = snappy-switcher --daemon

# Keybindings
bind = ALT, Tab, exec, snappy-switcher next
bind = ALT SHIFT, Tab, exec, snappy-switcher prev
bind = SUPER SHIFT,RETURN,exec, zen-browser # Browser
