# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Make every new window start floating by default. Specific rules below can still override.

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

windowrule = match:class ^(zen-browser)$, persistent_size off
windowrule = match:class ^(zen-browser)$, float on
windowrule = match:class ^(zen-browser)$, center on
windowrule = match:class ^(zen-browser)$, size (monitor_w*.85) (monitor_h*.85)

windowrule = size 850 500, match:class ^(kitty)$

windowrule = border_size 0, match:class ^(.*)$
windowrule = match:title ^(archmenu)$, float on
windowrule = match:title ^(archmenu)$, center on
windowrule = match:title ^(archmenu)$, size 500 200
windowrule = match:title ^(archmenu-about)$, float on
windowrule = match:title ^(archmenu-about)$, center on
windowrule = match:title ^(archmenu-about)$, size 800 500

windowrule = match:title ^(archmenu-install)$, float on
windowrule = match:title ^(archmenu-install)$, center on
windowrule = match:title ^(archmenu-install)$, size 900 600
