$background = 131315
$onBackground = e4e2e4
$surface = 131315
$surfaceDim = 131315
$surfaceBright = 39393b
$surfaceContainerLowest = 0e0e10
$surfaceContainerLow = 1b1b1d
$surfaceContainer = 1f1f21
$surfaceContainerHigh = 2a2a2c
$surfaceContainerHighest = 353436
$onSurface = e4e2e4
$surfaceVariant = 45474d
$onSurfaceVariant = c6c6cd
$outline = 8f9097
$outlineVariant = 45474d
$inverseSurface = e4e2e4
$inverseOnSurface = 303032
$shadow = 000000
$scrim = 000000
$surfaceTint = bcc6e2
$primary = bcc6e2
$primaryDim = d8e2ff
$onPrimary = 263046
$primaryContainer = 8993ad
$onPrimaryContainer = 222c41
$inversePrimary = 545e76
$primaryFixed = d8e2ff
$primaryFixedDim = bcc6e2
$onPrimaryFixed = 111b30
$onPrimaryFixedVariant = 3d475d
$secondary = c3c6d2
$secondaryDim = e0e2ee
$onSecondary = 2d303a
$secondaryContainer = 434751
$onSecondaryContainer = b2b5c1
$secondaryFixed = e0e2ee
$secondaryFixedDim = c3c6d2
$onSecondaryFixed = 181b24
$onSecondaryFixedVariant = 434751
$tertiary = debdd6
$tertiaryDim = fedbf6
$onTertiary = 3f293d
$tertiaryContainer = a88aa2
$onTertiaryContainer = 3b2438
$tertiaryFixed = fbd8f3
$tertiaryFixedDim = debdd6
$onTertiaryFixed = 291427
$onTertiaryFixedVariant = 573f54
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 6d7790
$secondaryPaletteKeyColor = 747782
$tertiaryPaletteKeyColor = a88aa2
$neutralPaletteKeyColor = 787779
$neutralVariantPaletteKeyColor = 76777e
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 6d7790
$secondary_paletteKeyColor = 747782
$tertiary_paletteKeyColor = a88aa2
$neutral_paletteKeyColor = 787779
$neutral_variant_paletteKeyColor = 76777e
$term0 = 353434
$term1 = 8d80ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 8dadd4
$term5 = a1a4ef
$term6 = 97cffc
$term7 = e8d3de
$term8 = ac9fa9
$term9 = a79dff
$term10 = 89ecff
$term11 = fff0f6
$term12 = aec3da
$term13 = bab9f8
$term14 = bae0ff
$term15 = ffffff
$rosewater = f4f0f9
$flamingo = e3dff5
$pink = d8daff
$mauve = aebdff
$red = acacff
$maroon = bbb9f0
$peach = e0c2f9
$yellow = d0f9f4
$green = c4e4ff
$teal = cae2ff
$sky = c5ddff
$sapphire = a6c9ff
$blue = 9dbdff
$lavender = b9ccff
$klink = 5a88cf
$klinkSelection = 5988cf
$kvisited = 6579dd
$kvisitedSelection = 637add
$knegative = 7f75ff
$knegativeSelection = 7d76ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 31b2ff
$kpositiveSelection = 2ab2ff
$text = e4e2e4
$subtext1 = c6c6cd
$subtext0 = 8f9097
$overlay2 = 7d7d83
$overlay1 = 6a6a6f
$overlay0 = 58595d
$surface2 = 48484c
$surface1 = 37373a
$surface0 = 252527
$base = 131315
$mantle = 131315
$crust = 121214
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
