-- Managed by ryoku-gpu. Empty by default: Hyprland uses its own GPU selection.
--
-- On a multi-GPU machine (a discrete Radeon or GeForce beside the CPU's
-- integrated GPU), `ryoku-gpu persist` rewrites this file with an
-- hl.env("AQ_DRM_DEVICES", ...) call that pins the strongest GPU as the primary
-- renderer. Reset to Hyprland's default selection with `ryoku-gpu disable`.
--
-- Changes take effect on the next Hyprland login (the env is read at start).
