-- Generated by HyprMod

-- Settings
hl.config({
    cursor = {
        persistent_warps = true,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            passes = 4,
            size = 4,
        },
        dim_inactive = true,
        fullscreen_opacity = 1.0,
        inactive_opacity = 1.0,
        rounding = 13,
        rounding_power = 3.0,
        shadow = {
            color = "0x40000000",
            offset = "0 0",
            render_power = 4,
        },
    },
    general = {
        border_size = 13,
        col = {
            active_border = "0xffbfc8cc",
        },
        gaps_in = 2,
        gaps_out = 5,
        layout = "dwindle",
    },
    gestures = {
        workspace_swipe_invert = true,
    },
    input = {
        accel_profile = "flat",
        force_no_accel = false,
        scroll_factor = 0.5,
        sensitivity = 0.3,
        emulate_discrete_scroll = 1,
        touchpad = {
            natural_scroll = true,
            disable_while_typing = false,
            clickfinger_behavior = true,
            scroll_factor = 0.5,
            tap_to_click = true,
            middle_button_emulation = true,
        },
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
