-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.9,
        blur = {
            passes = 4,
            size = 6,
        },
        dim_inactive = true,
        inactive_opacity = 0.9,
        rounding = 10,
        rounding_power = 2.0,
    },
    general = {
        gaps_in = 2,
        gaps_out = 5,
    },
    input = {
        accel_profile = "adaptive",
        scroll_factor = 0.8,
        sensitivity = 0.0,
        touchpad = {
            scroll_factor = 0.8,
        },
    },
})
