-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
            passes = 5,
            size = 5,
        },
        shadow = {
            enabled = true,
        },
    },
    general = {
        border_size = 2,
        col = {
            active_border = "0xff3d3846",
            inactive_border = "0xff3d3846",
        },
        gaps_in = 2,
        gaps_out = 5,
    },
    gestures = {
        workspace_swipe_cancel_ratio = 0.3,
        workspace_swipe_distance = 250,
    },
    input = {
        follow_mouse = 1,
    },
})
