-- Generated by Noctalia

local primary = "rgb(ffffff)"
local surface = "rgb(131313)"
local on_surface = "rgb(e2e2e2)"
local secondary = "rgb(c6c6c6)"
local on_secondary = "rgb(1b1b1b)"
local error = "rgb(ffb4ab)"
local on_error = "rgb(690005)"
local shadow = "rgb(000000)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        decoration = {
            shadow = {
                color = shadow,
            },
            glow = {
                color = shadow,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                gradients = true,
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = error,
        on_error = on_error,
        shadow = shadow,
    },
    apply_theme = apply_theme
}
