-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { gaps_in = 8, border_size = 1 },
  decoration = { rounding_power = 2.0, inactive_opacity = 0.97, border_part_of_window = false, blur = { passes = 4 }, shadow = { range = 20, render_power = 3 } },
  input = { kb_layout = "us", kb_variant = "", kb_options = "", numlock_by_default = true, follow_mouse = 1, accel_profile = "flat", touchpad = { natural_scroll = true } },
})

hl.curve("ryokuWobble", { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1 } } })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, bezier = "ryokuWobble" })
hl.curve("ryokuWobble", { type = "bezier", points = { { 0.45, 0.0 }, { 0.25, 1.0 } } })
hl.curve("dynamic-cursors-magnification", { type = "bezier", points = { { 0.3, 0.0 }, { 0.1, 1.0 } } })

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "14")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "14")

local function ryoku_plugin_loaded(name)
  for _, p in ipairs(hl.get_loaded_plugins()) do
    if p.name == name then return true end
  end
  return false
end

pcall(function()
  hl.plugin.load("/usr/lib/hyprland/plugins/dynamic-cursors.so")
  if ryoku_plugin_loaded("dynamic-cursors") then
    hl.config({ plugin = { dynamic_cursors = { enabled = true, mode = "stretch", shake = { enabled = true, base = 4.0 } } } })
  end
end)


hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 14")
end)
