misc {
    background_color = rgba(121314FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 36
        bar_padding = 12
        bar_button_padding = 10
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(121314FF)
        col.text = rgba(e3e2e2FF)

        # Put buttons on the right side
        bar_buttons_alignment = right
        bar_text_align = center

        # Windows 11-style controls
        # Close
        hyprbars-button = rgba(E81123CC), 16, ×, hyprctl dispatch killactive
        # Maximize / restore
        hyprbars-button = rgba(2B2B2B99), 16, □, hyprctl dispatch fullscreen 1
        # Minimize
        hyprbars-button = rgba(2B2B2B99), 16, -, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrule = border_color rgba(b9c9d0AA) rgba(b9c9d077), match:pin 1
