# --- Main Colors ---
background            #161217
foreground            #eae0e7
cursor                #eae0e7
cursor_text_color     #161217

selection_background  #524154
selection_foreground  #f3dbf3

url_color             #f5b7b1

# --- ANSI Colors ---
color0                #4c444c
color1                #ffb4ab
color2                #f5b7b1
color3                #d6c0d6
color4                #e8b6f0
color5                #f5b7b1
color6                #fbd7ff
color7                #eae0e7

color8                #988e97
color9                #ffdad6
color10               #ffdad6
color11               #f3dbf3
color12               #fbd7ff
color13               #ffdad6
color14               #f3dbf3
color15               #cfc3cd

# --- Starship Prompt Bubbles ---
color255              #5f3869
color254              #e8b6f0
color253              #524154
color252              #d6c0d6
color251              #673b37
color250              #f5b7b1
color249              #93000a
color248              #ffb4ab

color232              #fbd7ff
color233              #462151
color234              #f3dbf3
color235              #3a2b3d
color236              #ffdad6
color237              #4c2522
color238              #ffdad6
color239              #690005
color240              #fbd7ff

# Matched with unthemed light/dark
color243              #e8b6f0
color244              #ffb4ab
color245              #4c444c

# --- UI Elements ---
active_tab_foreground   #462151
active_tab_background   #e8b6f0
inactive_tab_foreground #fbd7ff
inactive_tab_background #5f3869

active_border_color     #e8b6f0
inactive_border_color   #988e97

# --- Marks ---
mark1_foreground        #2f0a3a
mark1_background        #fbd7ff
mark2_foreground        #241727
mark2_background        #f3dbf3
mark3_foreground        #33110e
mark3_background        #ffdad6
