# Main colors
background            #121415
foreground            #e3e2e4
cursor                #e3e2e4
cursor_text_color     #121415
selection_background  #3d4850
selection_foreground  #d6e2eb
url_color             #d9bddf

# ANSI colors
color0                #121415
color1                #ffb4ab
color2                #d9bddf
color3                #bdc8d1
color4                #accbe0
color5                #d9bddf
color6                #bdc8d1
color7                #e3e2e4
color8                #42474c
color9                #93000a
color10               #a288a8
color11               #3d4850
color12               #7795a9
color13               #3d4850
color14               #543f5b
color15               #c2c7cc

# Starship prompt bubbles
color255              #7795a9
color254              #accbe0
color253              #3d4850
color252              #bdc8d1
color251              #a288a8
color250              #d9bddf
color249              #93000a
color248              #ffb4ab
color232              #000000
color233              #143445
color234              #d6e2eb
color235              #273239
color236              #000000
color237              #3d2943
color238              #ffdad6
color239              #690005
color240              #000000
color243              #accbe0
color244              #ffb4ab
color245              #42474c

# UI elements
active_tab_foreground   #143445
active_tab_background   #accbe0
inactive_tab_foreground #000000
inactive_tab_background #7795a9
active_border_color     #accbe0
inactive_border_color   #8c9196

# Marks
mark1_foreground        #001e2d
mark1_background        #c7e7fd
mark2_foreground        #121d24
mark2_background        #d9e4ee
mark3_foreground        #27142d
mark3_background        #f6d9fc
