color0 #474747
color1 #ffb4ab
color2 #cabeff
color3 #c9c3dc
color4 #edb8cc
color5 #cabeff
color6 #c9c3dc
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #cabeff
color11 #c9c3dc
color12 #edb8cc
color13 #cabeff
color14 #c9c3dc
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #cabeff
inactive_border_color #474747
url_color             #cabeff

active_tab_foreground   #312075
active_tab_background   #cabeff
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
