color0 #4d463d
color1 #ffb4ab
color2 #dfc7ab
color3 #d1c4b7
color4 #cacdb1
color5 #dac3a7
color6 #d1c4b7
color7 #e7e1de
color8 #998f85
color9 #ffb4ab
color10 #dfc7ab
color11 #d1c4b7
color12 #cacdb1
color13 #dac3a7
color14 #d1c4b7
color15 #e7e1de

cursor                #e7e1de
cursor_text_color     #151311
background            #151311
foreground            #e7e1de
selection_foreground  #d0c5b9
selection_background  #4d463d
active_border_color   #dfc7ab
inactive_border_color #4d463d
url_color             #dfc7ab

active_tab_foreground   #3c2e1a
active_tab_background   #dfc7ab
inactive_tab_foreground #d0c5b9
inactive_tab_background #4d463d
cursor_trail_color      #d0c5b9
