color0 #000000
color1 #ffabb0
color2 #c1d9fa
color3 #b3aff1
color4 #d5aff1
color5 #edf3ff
color6 #e8e4ff
color7 #ffffff
color8 #313a44
color9 #ffabb0
color10 #c1d9fa
color11 #b3aff1
color12 #d5aff1
color13 #edf3ff
color14 #e8e4ff
color15 #ffffff

cursor                #ffffff
cursor_text_color     #000000
background            #000000
foreground            #ffffff
selection_foreground  #e7eaee
selection_background  #000000
active_border_color   #c1d9fa
inactive_border_color #000000
url_color             #c1d9fa

active_tab_foreground   #000000
active_tab_background   #c1d9fa
inactive_tab_foreground #e7eaee
inactive_tab_background #000000
cursor_trail_color      #e7eaee
