background #121414
foreground #e3e2e2
cursor #e3e2e2
cursor_text_color #121414
selection_background #8b9294
selection_foreground #e3e2e2
color0 #121414
color1 #ffb4ab
color2 #adccd5
color3 #e7bfa1
color4 #bdc8cc
color5 #adccd5
color6 #e7bfa1
color7 #e3e2e2
color8 #8b9294
color9 #ffb4ab
color10 #adccd5
color11 #e7bfa1
color12 #bdc8cc
color13 #adccd5
color14 #8b9294
color15 #ffffff
