background #16130f
foreground #eae1db
cursor #eae1db
cursor_text_color #16130f
selection_background #9c8e83
selection_foreground #eae1db
color0 #16130f
color1 #ffb4ab
color2 #eebe8d
color3 #a9cbe7
color4 #dcc2ab
color5 #eebe8d
color6 #a9cbe7
color7 #eae1db
color8 #9c8e83
color9 #ffb4ab
color10 #eebe8d
color11 #a9cbe7
color12 #dcc2ab
color13 #eebe8d
color14 #9c8e83
color15 #000000
